import React, { useEffect, useState } from 'react';
import { createUseStyles } from 'react-jss';
import { Theme, theme } from 'src/libs/theme';
import Input from '../../libs/core/Input/Input';
import { Button, Formix, Icon } from '../../libs/core';

const useStyles = createUseStyles<string, {}, any>((theme: Theme) => ({
  globalContainer: {
    minHeight: '100%',
    display: 'flex',
    justifyContent: 'flex-start',
    flexDirection: 'column',
    paddingBottom: theme.marginBase * 6,
  },
  container: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: theme.marginBase * 4,
    padding: theme.marginBase * 4,
    flexDirection: 'column',
    width: '100%',
    maxWidth: theme.boxWidth.large,
    margin: '0 auto',
  },
  balanceTitle: {
    ...theme.fonts.h2,
    color: theme.colors.black,
  },
  balanceContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: theme.marginBase,
    flexDirection: 'column',
  },
  balanceContainer2: {
    width: '100%',
    maxWidth: theme.boxWidth.tiny,
    padding: 20,
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: theme.marginBase,
    flexDirection: 'column',
  },
  balance: {
    ...theme.fonts.h3,
    color: theme.colors.black,
  },
  logOut: {
    ...theme.fonts.label,
    color: theme.colors.red,
    textDecoration: 'none',
  },
  speak: {
    backgroundColor: theme.colors.redLight,

    '&:hover': {
      backgroundColor: theme.colors.red,
    },
  },
}));

const sentences: string[] = [
  'Le chat gris dort sur le canapé bleu.',
  'La pluie tombe doucement sur le toit en tuiles.',
  'Marie lit un livre passionnant dans le jardin.',
  'Les enfants jouent joyeusement dans le parc.',
  "J'ai acheté des pommes rouges au marché ce matin.",
  'Le soleil brille et le ciel est sans nuages.',
  "Nous avons visité un musée d'art moderne hier.",
  'Le chien aboyait fort en voyant le facteur.',
  'Les fleurs du printemps embaument le jardin.',
  'Pierre et Paul sont allés à la montagne.',
  'Mon frère cuisine un délicieux gâteau au chocolat.',
  "La mer est calme et d'un bleu éclatant.",
  'Ils ont construit une maison en bois près du lac.',
  'Sophie porte une robe jaune et des chaussures blanches.',
  'Le vent souffle fort sur la colline.',
  'Les feuilles des arbres deviennent rouges en automne.',
  "J'ai perdu mes clés en rentrant chez moi.",
  'Nous avons regardé un film amusant hier soir.',
  'La voiture rouge est garée devant la maison.',
  'Il fait très chaud en été dans cette région.',
  "L'ordinateur portable de Julie est neuf et performant.",
  'La lune éclaire la nuit noire.',
  'Nous avons fait une longue promenade en forêt.',
  'La bibliothèque est pleine de livres intéressants.',
  'Le bébé dort paisiblement dans son berceau.',
  'Le marché de Noël est très animé cette année.',
  'La neige recouvre les toits et les arbres.',
  "J'aime écouter de la musique en travaillant.",
  'Ils partent en vacances au bord de la mer.',
  'Mon oncle habite dans une grande maison à la campagne.',
  'Le fromage français est célèbre dans le monde entier.',
  'La maîtresse a donné des devoirs à faire pour demain.',
  'Nous avons mangé une pizza délicieuse hier soir.',
  'Le jardinier plante des fleurs au printemps.',
  'Les élèves étudient sérieusement pour leurs examens.',
  "Le bus arrive à l'arrêt dans cinq minutes.",
  'La soupe chaude est parfaite pour les jours froids.',
  'Les oiseaux chantent tôt le matin.',
  'Mon cousin a un chat noir très mignon.',
  "La fête d'anniversaire de Julie était fantastique.",
  'Le feu de camp éclaire la nuit sombre.',
  'Le docteur consulte ses patients tous les matins.',
  'La mer Méditerranée est très belle en été.',
  'Le ciel étoilé est magnifique ce soir.',
  'Le boulanger prépare du pain frais chaque jour.',
  'Nous avons décoré le sapin de Noël ensemble.',
  'La rivière coule doucement à travers la vallée.',
  "Le train partira à l'heure prévue.",
  'Ils ont joué au tennis pendant deux heures.',
  'Mon grand-père raconte des histoires passionnantes.',
  'Le dîner est servi à huit heures précises.',
  'La cascade est haute et impressionnante.',
  'Les enfants courent dans le champ de fleurs.',
  "Le camion de livraison est en retard aujourd'hui.",
  'Elle porte un chapeau rouge et des lunettes de soleil.',
  'Le vent du nord est froid en hiver.',
  "Nous avons visité Paris l'été dernier.",
  'La petite fille a un joli sourire.',
  'Le restaurant sert des plats délicieux.',
  'Le livreur apporte le colis à la porte.',
  'Le marché aux poissons est très fréquenté.',
  'La tour Eiffel est un symbole de Paris.',
  'Le chaton joue avec une pelote de laine.',
  'La plage est couverte de coquillages.',
  'Ils ont assisté à un concert de jazz.',
  'Le pêcheur a attrapé un gros poisson.',
  'La fontaine au centre du parc est jolie.',
  'Les élèves dessinent des paysages colorés.',
  'Le renard traverse la route rapidement.',
  'Mon amie habite dans un immeuble moderne.',
  'Le pâtissier prépare des gâteaux appétissants.',
  'La maison est entourée de beaux arbres.',
  'Le vélo de Jean est tout neuf.',
  'Nous avons exploré la grotte mystérieuse.',
  'Le lapin mange des carottes dans le jardin.',
  'La table est mise pour le dîner.',
  "Les vacances d'été approchent à grands pas.",
  'Le navire navigue sur une mer agitée.',
  'Les moutons broutent dans le pré.',
  'Le théâtre présente une pièce classique.',
  'La fête foraine est pleine de lumières.',
  'Le coq chante tôt le matin.',
  'La bibliothèque ferme à six heures.',
  'Ils ont acheté des billets pour le spectacle.',
  'Le facteur distribue le courrier chaque jour.',
  'Le ciel est gris et il va pleuvoir.',
  'Les enfants dessinent avec des crayons de couleur.',
  "Le canard nage dans l'étang paisiblement.",
  'La soupe de légumes est très nutritive.',
  'Les montagnes sont couvertes de neige en hiver.',
  'Le chat chasse une souris dans le jardin.',
  'La boulangerie est fermée le dimanche.',
  "Le soleil se couche à l'horizon.",
  'La gare est très animée le matin.',
  'Le café au lait est mon préféré.',
  'Ils jouent au football dans la rue.',
  'Le médecin prescrit des médicaments.',
  'La piscine est chauffée en hiver.',
  'Le tigre est un animal majestueux.',
  'Nous avons peint les murs en bleu clair.',
  'Les éclairs illuminent le ciel obscurci par les nuages menaçants.',
  'Le bibliothécaire a rangé les nouveaux ouvrages sur les étagères du haut.',
  'Nous avons dégusté des macarons à la framboise, délicieusement sucrés et fondants.',
  "La conférencière a captivé l'audience avec des anecdotes historiques fascinantes.",
  'Les élèves ont réalisé une maquette représentant un volcan en éruption.',
  'Le château médiéval domine la vallée et offre une vue imprenable.',
  'Il faut composter son billet avant de monter dans le train.',
  'La symphonie de Beethoven est interprétée par un orchestre renommé.',
  "Les roses du jardin embaument l'air frais du matin.",
  'Nous avons escaladé les montagnes pour atteindre le sommet enneigé.',
  'La pâtisserie propose des éclairs au chocolat et des tartelettes aux fraises.',
  'Les scientifiques ont découvert une nouvelle espèce de papillon dans la forêt tropicale.',
  "Les vacances d'hiver en montagne sont synonymes de ski et de chocolat chaud.",
  "Les élèves participent à un concours de mathématiques à l'échelle nationale.",
  "La collection d'art moderne du musée est absolument impressionnante.",
  'Nous avons observé les étoiles à travers un télescope puissant.',
  'Le compositeur a terminé sa symphonie après des années de travail acharné.',
  'Le peintre a capturé la lumière du coucher de soleil avec une grande précision.',
  'Les agriculteurs récoltent le blé sous un ciel sans nuages.',
  'La pièce de théâtre a été saluée par des applaudissements enthousiastes.',
  'Les astronautes se préparent pour une mission vers Mars.',
  'La ville médiévale est entourée de remparts bien conservés.',
  'La lune de miel sur une île tropicale était inoubliable.',
  'Les étudiants révisent leurs notes avant les examens finaux.',
  "Les vitraux de la cathédrale projettent des couleurs éclatantes à l'intérieur.",
  'Le chevalier a bravé les dangers pour sauver la princesse.',
  'La recherche scientifique avance grâce à des découvertes innovantes.',
  'Les marins ont navigué sur des mers tumultueuses pendant des mois.',
  'Le violoniste joue une mélodie mélancolique qui touche le cœur.',
  'Les plongeurs explorent les récifs coralliens à la recherche de trésors.',
  'Les enfants construisent un château de sable sur la plage.',
  'Le poète écrit des vers émouvants inspirés par la nature.',
  'Les architectes conçoivent des bâtiments modernes et écologiques.',
  'Le boulanger pétrit la pâte avec des gestes experts et rapides.',
  "Les festivités du Nouvel An incluent des feux d'artifice spectaculaires.",
  'Les plongeurs ont découvert une épave vieille de plusieurs siècles.',
  'Le botaniste étudie la flore alpine pour ses recherches.',
  'La tempête de neige a paralysé la ville pendant plusieurs jours.',
  'Les musiciens répètent sans relâche pour le concert de ce soir.',
  'Les étoiles filantes traversent le ciel lors de la nuit des Perséides.',
  "Le joueur d'échecs planifie chaque coup avec une grande concentration.",
  'Les aventuriers traversent la jungle à la recherche de civilisations perdues.',
  'Les manuscrits anciens sont conservés dans une bibliothèque climatisée.',
  'Les chefs cuisiniers préparent des plats gastronomiques avec des ingrédients frais.',
  'Les pirates naviguaient sur les mers à la recherche de trésors.',
  'Les archéologues ont découvert des fossiles rares dans le désert.',
  "La brume matinale enveloppe le paysage d'une atmosphère mystérieuse.",
  'Les écoliers écrivent des rédactions sur des sujets variés.',
  'Les plongeurs rencontrent des créatures marines fascinantes dans les profondeurs.',
  'Le horloger répare des montres anciennes avec une grande minutie.',
  'Les pèlerins marchent vers le sanctuaire en chantant des hymnes.',
  'Les choristes répètent les chants pour le concert de Noël.',
  'Les explorateurs cartographient des territoires inconnus avec précision.',
  'Les abeilles butinent les fleurs pour produire du miel.',
  "Le potier façonne l'argile pour créer des objets utilitaires et artistiques.",
  'Les acteurs répètent leurs répliques avant la première de la pièce.',
  'Le sculpteur taille la pierre avec une grande habileté.',
  'Les oiseaux migrateurs parcourent des milliers de kilomètres chaque année.',
  'Le forgeron façonne le métal avec une grande expertise.',
  'Les céramistes créent des pièces uniques en utilisant des techniques traditionnelles.',
  "Les randonneurs suivent un sentier escarpé jusqu'au sommet.",
  'Les plongeurs photographient des poissons multicolores dans les récifs.',
  'Le bibliophile collectionne des livres rares et précieux.',
  "Les poètes se réunissent pour partager leurs œuvres et s'inspirer mutuellement.",
  'Les chasseurs de trésors explorent des épaves sous-marines anciennes.',
  'Les artistes de rue dessinent des fresques colorées sur les murs de la ville.',
  "Les scientifiques étudient l'impact du changement climatique sur les écosystèmes.",
  'Les écrivains de science-fiction imaginent des mondes futurs fascinants.',
  'Les alpinistes affrontent des conditions extrêmes pour atteindre le sommet.',
  'Les paysans travaillent dur pour récolter les fruits de leur labeur.',
  'Les compositeurs créent des symphonies qui traversent les âges.',
  'Les musiciens de jazz improvisent avec une virtuosité impressionnante.',
  'Les conteurs narrent des légendes anciennes autour du feu de camp.',
  'Les pêcheurs remontent des filets pleins de poissons argentés.',
  'Les moines copistes enluminaient des manuscrits avec des motifs détaillés.',
  'Les spéléologues explorent des grottes profondes et mystérieuses.',
  'Les plongeurs nagent avec des tortues dans les eaux tropicales.',
  'Les chefs étoilés préparent des repas somptueux pour leurs clients.',
  'Les apiculteurs récoltent le miel des ruches avec précaution.',
  'Les inventeurs travaillent sur des prototypes innovants dans leurs ateliers.',
  'Les romanciers écrivent des histoires captivantes qui transportent les lecteurs.',
  'Les danseurs interprètent une chorégraphie complexe avec grâce.',
  'Les astronomes scrutent les étoiles à la recherche de nouvelles planètes.',
  'Les ingénieurs conçoivent des ponts impressionnants reliant les rives.',
  'Les magiciens réalisent des tours de passe-passe fascinants.',
  'Les chefs pâtissiers créent des desserts élégants et délicieux.',
  'Les acrobates exécutent des numéros spectaculaires avec agilité.',
  'Les tisserands créent des étoffes aux motifs délicats et colorés.',
  'Les scientifiques analysent des échantillons dans leurs laboratoires modernes.',
  'Les artistes peintres capturent des scènes de la vie quotidienne avec talent.',
  'Les historiens étudient des documents anciens pour comprendre le passé.',
  'Les bijoutiers façonnent des bijoux en or et en argent.',
  'Les écrivains de romans policiers imaginent des intrigues captivantes.',
  'Les chercheurs en biologie marine étudient les comportements des animaux aquatiques.',
  'Les illustrateurs dessinent des images pour des livres pour enfants.',
  'Les alchimistes cherchaient autrefois la pierre philosophale.',
  'Les ornithologues observent les oiseaux dans leur habitat naturel.',
  'Les archivistes conservent des documents précieux dans des conditions optimales.',
  'Les marionnettistes manipulent des marionnettes avec habileté.',
  'Les ébénistes travaillent le bois pour créer des meubles élégants.',
  'Les tatoueurs dessinent des motifs sur la peau avec précision.',
  'Les éleveurs de chevaux veillent sur leurs bêtes avec dévouement.',
  'Les photographes capturent des instants fugaces avec leur appareil.',
  'Les calligraphes écrivent des textes avec une grande beauté.',
  'Les archéologues fouillent des sites anciens à la recherche de vestiges.',
  'La couturière confectionne des vêtements sur mesure pour ses clients.',
  'Je suis allé au cinéma avec mes amis hier soir.',
  'Elle a acheté une nouvelle voiture rouge.',
  'Ils ont mangé une pizza au restaurant italien.',
  'Nous avons visité le musée d’histoire naturelle.',
  'Tu as lu un livre passionnant ce week-end.',
  'Il a regardé un film d’action à la télévision.',
  'L´école est fermée pendant les vacances de Noël.',
  'Les explorateurs polaires ont survécu à des températures glaciales pendant des mois.',
  'Le violoniste prodige a donné un concert qui a ébloui le public.',
  "Les archéologues ont mis au jour des ruines d'une civilisation antique.",
  'La chorale a interprété un requiem avec une grande émotion.',
  'Le compositeur a achevé son opéra après des années de recherche musicale.',
  'Les botanistes classent les plantes selon des critères très précis.',
  'Le philosophe a publié un traité sur la nature de la réalité.',
  'Les architectes conçoivent des gratte-ciels qui défient la gravité.',
  "Le médecin a diagnostiqué une maladie rare après une série d'examens approfondis.",
  'Les linguistes étudient les langues anciennes pour comprendre les cultures passées.',
  'Le journaliste a couvert un conflit armé dans une zone dangereuse.',
  'Les climatologues prévoient des changements drastiques dans les conditions météorologiques.',
  'Le chirurgien a réalisé une opération complexe avec succès.',
  'Les généticiens étudient les mutations pour comprendre les maladies héréditaires.',
  'Le mathématicien a résolu une équation considérée comme insoluble.',
  "Les astronomes ont découvert une nouvelle galaxie à des millions d'années-lumière.",
  'Le romancier a écrit un best-seller qui a captivé des millions de lecteurs.',
  'Les chimistes analysent les composés pour créer de nouveaux médicaments.',
  'Le sculpteur a créé une œuvre monumentale en marbre.',
  'Les historiens débattent sur les causes des grandes révolutions.',
  'Le chef étoilé a concocté un menu dégustation impressionnant.',
  'Les biologistes marins étudient les écosystèmes des abysses océaniques.',
  'Le cinéaste a tourné un film qui a remporté de nombreux prix.',
  'Les ethnologues étudient les coutumes des tribus isolées.',
  'Le pianiste a interprété une sonate de Beethoven avec brio.',
  "Les physiciens théoriques explorent les mystères de l'univers.",
  'Le couturier a présenté une collection qui a fait sensation à la Fashion Week.',
  'Les neurologues cherchent à comprendre le fonctionnement du cerveau.',
  'Le diplomate a négocié un accord de paix historique.',
  'Les ingénieurs aérospatiaux développent des technologies pour les voyages interstellaires.',
  'Le sommelier a recommandé un vin exceptionnel pour accompagner le repas.',
  "Les géologues étudient les formations rocheuses pour retracer l'histoire de la Terre.",
  "Le dramaturge a écrit une pièce qui explore les complexités de l'âme humaine.",
  "Les anthropologues analysent les fossiles pour reconstituer l'évolution humaine.",
  'Le maître de ballet a chorégraphié une performance époustouflante.',
  'Les écologistes militent pour la protection des espèces en voie de disparition.',
  'Le chercheur a publié une étude révolutionnaire sur les cellules souches.',
  'Les juristes débattent des implications des nouvelles lois.',
  'Le volcanologue a étudié les éruptions pour prévoir les futures activités volcaniques.',
  'Les psychiatres travaillent avec des patients souffrant de troubles mentaux graves.',
  "Le musicologue a découvert des partitions inédites d'un compositeur célèbre.",
  'Les océanographes cartographient les fonds marins avec une grande précision.',
  "Le critique d'art a analysé les œuvres d'un peintre controversé.",
  'Les sociologues examinent les dynamiques des communautés urbaines.',
  'Le toxicologue étudie les effets des substances chimiques sur la santé.',
  'Les archéozoologues identifient les ossements pour comprendre les interactions entre humains et animaux.',
  'Le politologue a écrit un essai sur les systèmes de gouvernance.',
  'Les cryptologues déchiffrent des codes complexes pour assurer la sécurité des informations.',
  'Le chef pâtissier a élaboré des desserts sophistiqués pour le banquet royal.',
  'Les climatologues analysent les carottes de glace pour comprendre le climat passé.',
  'Le neurochirurgien a réalisé une intervention délicate sur la moelle épinière.',
  'Les astrophysiciens recherchent des exoplanètes habitables dans notre galaxie.',
  "Le restaurateur d'art a restauré un tableau endommagé de la Renaissance.",
  'Les zoologistes étudient les comportements des animaux en captivité et dans la nature.',
  'Le réalisateur a tourné un documentaire sur la vie sauvage en Afrique.',
  'Les mycologues cataloguent les différentes espèces de champignons.',
  'Le poète a écrit des vers en hommage à la beauté de la nature.',
  'Les démographes analysent les tendances de la population mondiale.',
  'Le chirurgien plasticien a effectué une reconstruction faciale complexe.',
  "Les acousticiens travaillent à l'amélioration des systèmes de sonorisation.",
  'Le séismologue a prédit un tremblement de terre grâce à des techniques avancées.',
  "Les psychanalystes explorent l'inconscient à travers les rêves.",
  "Le généalogiste a tracé l'arbre généalogique d'une famille noble.",
  'Les économistes étudient les impacts des politiques fiscales sur la société.',
  "Le cosmologiste enquête sur l'origine et l'évolution de l'univers.",
  'Les paléontologues reconstituent les squelettes de dinosaures avec précision.',
  'Le botaniste a découvert une nouvelle espèce de plante carnivore.',
  'Les lexicographes compilent des dictionnaires pour documenter les langues.',
  'Le biochimiste a isolé une enzyme clé dans la digestion.',
  "Les historiens de l'art analysent les influences culturelles dans les œuvres d'art.",
  'Le musicothérapeute utilise la musique pour aider les patients à se rétablir.',
  'Les astronomes amateurs construisent des télescopes pour observer les étoiles.',
  'Le directeur de théâtre a monté une pièce classique avec une nouvelle interprétation.',
  'Les océanographes étudient les courants marins pour comprendre les climats.',
  'Le psychanalyste a interprété les rêves de ses patients pour révéler des traumatismes.',
  'Les linguistes cherchent à préserver les langues en voie de disparition.',
  "Le paléontologue a mis au jour des fossiles datant de millions d'années.",
  'Les philosophes débattent des questions éthiques dans la société moderne.',
  'Le neurologue a mené des recherches sur les troubles neurodégénératifs.',
  'Les météorologues utilisent des modèles pour prévoir les phénomènes climatiques extrêmes.',
  'Le biophysicien étudie les mécanismes des cellules vivantes.',
  "Les historiens de la musique tracent l'évolution des styles musicaux.",
  'Le chirurgien cardiaque a effectué une transplantation avec succès.',
  'Les physiciens nucléaires travaillent sur des projets de fusion pour une énergie propre.',
  'Le chercheur en intelligence artificielle développe des algorithmes avancés.',
  'Les économistes prédisent les tendances du marché mondial.',
  'Le théoricien du complot a élaboré des hypothèses controversées.',
  'Les démographes prévoient une augmentation significative de la population urbaine.',
  'Le thérapeute utilise des méthodes innovantes pour traiter les phobies.',
  'Les herpétologistes étudient les reptiles et les amphibiens.',
  'Le chimiste a synthétisé un nouveau composé avec des propriétés uniques.',
  'Les sociologues analysent les effets des réseaux sociaux sur les interactions humaines.',
  'Le cybernéticien travaille sur les interfaces homme-machine.',
  'Les historiens économiques étudient les cycles de croissance et de récession.',
  'Le neurobiologiste recherche les causes des maladies neurodégénératives.',
  'Je vous écris pour confirmer notre rendez-vous de demain matin.',
  'Veuillez trouver ci-joint le rapport annuel de notre entreprise.',
  'Je souhaiterais discuter des détails du projet lors de notre prochaine réunion.',
  "Merci de bien vouloir m'envoyer les documents manquants dès que possible.",
  'Je vous remercie de votre rapide réponse à ma demande.',
  'Nous devons organiser une réunion pour clarifier les objectifs du trimestre.',
  'Je vous informe que la réunion prévue est reportée à une date ultérieure.',
  'Pouvez-vous me confirmer votre disponibilité pour un entretien la semaine prochaine ?',
  'Je vous remercie pour votre collaboration sur ce dossier important.',
  'Merci de bien vouloir prendre en compte mes commentaires avant de finaliser le rapport.',
  'Nous avons le plaisir de vous annoncer la nomination de notre nouveau directeur.',
  'Je vous prie de bien vouloir approuver les modifications apportées au contrat.',
  "Pouvez-vous m'envoyer le devis actualisé pour la semaine prochaine ?",
  'Nous avons constaté une erreur dans la facture précédente.',
  'Merci de nous fournir les informations nécessaires avant la fin de la journée.',
  'Je souhaiterais organiser une visioconférence pour discuter des prochains étapes.',
  'Nous avons besoin de votre approbation avant de lancer le projet.',
  'Je vous invite à participer à la formation prévue la semaine prochaine.',
  'Merci de bien vouloir transférer ce message à toutes les personnes concernées.',
  'Je vous informe que nous avons atteint nos objectifs de vente pour ce trimestre.',
  'Veuillez nous envoyer les détails du paiement dès que possible.',
  'Nous aimerions recevoir votre feedback sur le dernier prototype.',
  'Pouvez-vous vérifier les données et me faire un retour rapidement ?',
  'Je suis disponible pour une réunion téléphonique à partir de 14 heures.',
  'Merci de confirmer votre présence à la conférence de la semaine prochaine.',
  'Nous avons le plaisir de vous inviter à notre événement annuel.',
  "Veuillez trouver ci-joint l'ordre du jour de la prochaine réunion.",
  'Merci de bien vouloir respecter les délais indiqués dans le contrat.',
  'Nous avons besoin de votre accord écrit pour finaliser cette transaction.',
  'Je vous remercie de prendre en considération ma demande urgente.',
  'Pouvez-vous nous envoyer les échantillons avant la fin de la semaine ?',
  'Je vous prie de bien vouloir noter que mon adresse e-mail a changé.',
  'Nous devons discuter des révisions apportées au plan de projet.',
  'Merci de bien vouloir confirmer la réception de ce message.',
  'Je vous informe que votre demande a été approuvée.',
  "Nous avons besoin de plus d'informations pour compléter notre analyse.",
  'Merci de bien vouloir répondre à ce questionnaire avant le 15 juin.',
  'Nous avons le plaisir de vous informer de notre nouvelle collaboration.',
  'Je souhaiterais prendre rendez-vous pour discuter de votre proposition.',
  'Merci de bien vouloir envoyer le compte rendu de la réunion précédente.',
  "Nous avons le plaisir de vous annoncer l'ouverture de notre nouveau bureau.",
  'Je vous remercie pour votre compréhension et votre soutien continu.',
  'Pouvez-vous me faire parvenir le plan de travail mis à jour ?',
  "Nous devons organiser une réunion d'équipe pour discuter des priorités.",
  "Merci de bien vouloir me tenir informé de l'avancement du projet.",
  'Je vous prie de bien vouloir signer et retourner le contrat ci-joint.',
  'Nous avons identifié plusieurs points à améliorer dans votre proposition.',
  "Merci de bien vouloir m'envoyer les coordonnées de votre contact.",
  "Je vous écris pour vous informer d'un changement de dernière minute.",
  'Nous avons le plaisir de vous inviter à notre soirée de gala.',
  "Merci de bien vouloir compléter le formulaire d'inscription ci-joint.",
  'Je vous prie de bien vouloir prendre en compte ma demande de congé.',
  'Nous avons besoin de votre expertise pour résoudre ce problème technique.',
  'Merci de bien vouloir nous faire parvenir votre devis détaillé.',
  'Je vous informe que le projet a été approuvé par la direction.',
  'Pouvez-vous vérifier les chiffres et me confirmer leur exactitude ?',
  'Nous avons le plaisir de vous inviter à notre webinaire sur ce sujet.',
  'Merci de bien vouloir me rappeler dès que vous avez un moment.',
  'Je vous remercie pour votre aide précieuse dans ce dossier complexe.',
  "Nous avons besoin de votre retour sur le dernier rapport d'audit.",
  'Merci de bien vouloir noter que notre réunion est avancée à 10 heures.',
  'Je souhaiterais discuter des implications financières de cette décision.',
  "Pouvez-vous m'envoyer le tableau récapitulatif des ventes mensuelles ?",
  'Nous avons constaté un retard dans la livraison de nos commandes.',
  'Merci de bien vouloir préparer une présentation pour notre prochaine réunion.',
  'Je vous informe que nous avons reçu les documents demandés.',
  "Pouvez-vous m'envoyer les coordonnées des participants à la conférence ?",
  'Nous avons le plaisir de vous annoncer le lancement de notre nouveau produit.',
  'Merci de bien vouloir réviser le document et me faire part de vos commentaires.',
  'Je vous prie de bien vouloir confirmer votre disponibilité pour cette date.',
  'Nous avons besoin de votre accord avant de procéder à cette étape.',
  "Merci de bien vouloir m'envoyer une copie du contrat signé.",
  'Je vous informe que notre réunion hebdomadaire est annulée.',
  'Pouvez-vous me fournir une estimation des coûts pour ce projet ?',
  'Nous devons discuter des résultats du dernier sondage.',
  'Merci de bien vouloir me tenir informé des prochaines étapes.',
  'Je souhaiterais planifier une rencontre pour discuter de votre proposition.',
  "Nous avons le plaisir de vous annoncer l'obtention d'un nouveau contrat.",
  "Merci de bien vouloir m'envoyer les fichiers nécessaires pour l'analyse.",
  'Je vous prie de bien vouloir approuver les modifications apportées.',
  'Nous devons organiser une session de formation pour les nouveaux employés.',
  'Merci de bien vouloir me faire parvenir le compte rendu de la réunion.',
  'Je vous informe que notre nouveau site web est maintenant en ligne.',
  "Pouvez-vous m'envoyer les résultats des tests dès que possible ?",
  'Nous avons le plaisir de vous inviter à notre séminaire annuel.',
  'Merci de bien vouloir préparer le rapport pour la fin de la semaine.',
  'Je souhaiterais discuter des options possibles pour ce projet.',
  'Nous avons besoin de votre approbation pour lancer cette campagne.',
  'Merci de bien vouloir me fournir une mise à jour régulière.',
  'Je vous prie de bien vouloir confirmer votre participation à cet événement.',
  'Nous devons discuter des stratégies pour améliorer notre performance.',
  'Merci de bien vouloir nous faire parvenir votre proposition détaillée.',
  'Je vous informe que nous avons reçu vos documents.',
  'Pouvez-vous vérifier les informations et me confirmer leur exactitude ?',
  "Nous avons le plaisir de vous annoncer la tenue d'un atelier.",
  'Merci de bien vouloir répondre à ce message dès que possible.',
  'Je souhaiterais organiser une réunion pour discuter des prochaines étapes.',
];

export const Spelling = () => {
  const classes = useStyles({ theme });

  const getRandomSentence = () => {
    const randomIndex = Math.floor(Math.random() * sentences.length);
    return sentences[randomIndex];
  };

  //function to make computer or phone speak text
  const speak = (text: string) => {
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = 'fr-FR';
    speechSynthesis.speak(utterance);
  };

  const [sentence, setSentence] = useState<string>(getRandomSentence());
  const [error, setError] = useState<string>('');
  const [reset, setRest] = useState<boolean>(false);

  useEffect(() => {
    speak(sentence);
  }, [sentence]);

  return (
    <div className={classes.globalContainer}>
      <div className={classes.container}>
        <div className={classes.balanceContainer}>
          <h2 className={classes.balanceTitle}>Spelling Test</h2>
        </div>
      </div>
      <Formix
        initialValues={{ answer: '' }}
        onSubmit={async (values, formikHelpers) => {
          if (values.answer === sentence) {
            setSentence(getRandomSentence());
            await formikHelpers.setFieldValue('answer', '');
            setError('');
            setRest(!reset);
          } else {
            setError(sentence);
          }
        }}
        className={classes.balanceContainer2}
      >
        <Button
          color="blue"
          text="Speak"
          type="button"
          icon={Icon.jenkins}
          className={classes.speak}
          onClick={() => {
            speak(sentence);
          }}
        />
        <br />
        <Input
          title="Answer"
          autoSize
          name="answer"
          error={error}
          reset={reset}
        />
        <Button text="Check" full type="submit" />
      </Formix>
    </div>
  );
};
